"""
crop.py
-------
FastAPI router for the Crop Recommendation feature.

Loads a pre-trained Random Forest Classifier (crop_model.pkl) and its
label encoder (crop_label_encoder.pkl) from backend/models/, and exposes
a POST endpoint that predicts the best crop to grow given soil and
climate conditions.

NOTE: The model files are NOT generated by this project. Place your own
      trained files at:
          backend/models/crop_model.pkl
          backend/models/crop_label_encoder.pkl
"""

import os
import joblib
import numpy as np
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from database import insert_crop_prediction, get_crop_predictions

router = APIRouter(prefix="/api/crop", tags=["Crop Recommendation"])

MODELS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models")
CROP_MODEL_PATH = os.path.join(MODELS_DIR, "random_forest.pkl")
CROP_LABEL_ENCODER_PATH = os.path.join(MODELS_DIR, "label_encoder.pkl")

# Models are loaded lazily so the API can still start even if the
# .pkl files have not been placed yet. They are cached after first load.
_crop_model = None
_crop_label_encoder = None


def _load_crop_artifacts():
    """
    Load the crop model and label encoder into module-level caches.
    Raises a clear error if the files are missing.
    """
    global _crop_model, _crop_label_encoder

    _crop_model = joblib.load(CROP_MODEL_PATH)
    _crop_label_encoder = joblib.load(CROP_LABEL_ENCODER_PATH)

    return _crop_model, _crop_label_encoder


class CropInput(BaseModel):
    """Request schema for crop recommendation."""
    nitrogen: float = Field(..., ge=0, description="Nitrogen content in soil (N)")
    phosphorus: float = Field(..., ge=0, description="Phosphorus content in soil (P)")
    potassium: float = Field(..., ge=0, description="Potassium content in soil (K)")
    temperature: float = Field(..., description="Average temperature in Celsius")
    humidity: float = Field(..., ge=0, le=100, description="Relative humidity in %")
    ph: float = Field(..., ge=0, le=14, description="Soil pH value")
    rainfall: float = Field(..., ge=0, description="Rainfall in mm")


class CropOutput(BaseModel):
    """Response schema for crop recommendation."""
    predicted_crop: str
    message: str


@router.post("/predict", response_model=CropOutput)
def predict_crop(payload: CropInput):
    """
    Predict the most suitable crop for the given soil and climate
    conditions, then persist the result to the database.
    """
    try:
        model, label_encoder = _load_crop_artifacts()

        features = np.array([[
            payload.nitrogen,
            payload.phosphorus,
            payload.potassium,
            payload.temperature,
            payload.humidity,
            payload.ph,
            payload.rainfall,
        ]])

        prediction_encoded = model.predict(features)
        predicted_crop = label_encoder.inverse_transform(prediction_encoded)[0]
        predicted_crop = str(predicted_crop).title()

        insert_crop_prediction(
            nitrogen=payload.nitrogen,
            phosphorus=payload.phosphorus,
            potassium=payload.potassium,
            temperature=payload.temperature,
            humidity=payload.humidity,
            ph=payload.ph,
            rainfall=payload.rainfall,
            predicted_crop=predicted_crop,
        )

        return CropOutput(
            predicted_crop=predicted_crop,
            message=f"Based on the provided soil and climate data, '{predicted_crop}' "
                    f"is the recommended crop to grow."
        )

    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Crop prediction failed: {str(e)}")


@router.get("/history")
def crop_history(limit: int = 50):
    """Return the most recent crop prediction records."""
    try:
        return {"history": get_crop_predictions(limit=limit)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch crop history: {str(e)}")
