"""
yield.py
--------
FastAPI router for the Crop Yield Prediction feature.

Loads a pre-trained Random Forest Regressor (yield_model.pkl) plus two
label encoders (area_encoder.pkl, item_encoder.pkl) from backend/models/,
and exposes a POST endpoint that predicts crop yield.

NOTE: 'yield' is a reserved Python keyword, so this module must be
      imported dynamically (see main.py), e.g.:
          import importlib
          yield_module = importlib.import_module("yield")
          router = yield_module.router

NOTE: The model files are NOT generated by this project. Place your own
      trained files at:
          backend/models/yield_model.pkl
          backend/models/area_encoder.pkl
          backend/models/item_encoder.pkl
"""

import os
import joblib
import numpy as np
from fastapi import APIRouter, HTTPException
from pydantic import BaseModel, Field

from database import insert_yield_prediction, get_yield_predictions

router = APIRouter(prefix="/api/yield", tags=["Yield Prediction"])

MODELS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models")
YIELD_MODEL_PATH = os.path.join(MODELS_DIR, "random_forest_regressor.pkl")
AREA_ENCODER_PATH = os.path.join(MODELS_DIR, "area_encoder.pkl")
ITEM_ENCODER_PATH = os.path.join(MODELS_DIR, "item_encoder.pkl")

# Lazily loaded and cached model artifacts.
_yield_model = None
_area_encoder = None
_item_encoder = None


def _load_yield_artifacts():
    """
    Load the yield model and its encoders into module-level caches.
    Raises a clear error if any required file is missing.
    """
    global _yield_model, _area_encoder, _item_encoder
    _yield_model = joblib.load(YIELD_MODEL_PATH)

    
    _area_encoder = joblib.load(AREA_ENCODER_PATH)

    
    _item_encoder = joblib.load(ITEM_ENCODER_PATH)

    return _yield_model, _area_encoder, _item_encoder


class YieldInput(BaseModel):
    """Request schema for yield prediction."""
    area: str = Field(..., description="Country / region name, e.g. 'India'")
    item: str = Field(..., description="Crop item name, e.g. 'Wheat'")
    year: int = Field(..., ge=1900, le=2100, description="Year of cultivation")
    rainfall: float = Field(..., ge=0, description="Average rainfall in mm/year")
    pesticides: float = Field(..., ge=0, description="Pesticide usage in tonnes")
    temperature: float = Field(..., description="Average temperature in Celsius")


class YieldOutput(BaseModel):
    """Response schema for yield prediction."""
    predicted_yield: float
    unit: str = "hg/ha"
    message: str


def _safe_encode(encoder, value: str, field_name: str) -> int:
    """
    Encode a categorical value using a fitted LabelEncoder, raising a
    clear, user-friendly error if the value was not seen during training.
    """
    try:
        return int(encoder.transform([value])[0])
    except ValueError:
        known_values = ", ".join(sorted(map(str, encoder.classes_))[:15])
        raise HTTPException(
            status_code=400,
            detail=(
                f"Unknown {field_name} value '{value}'. This value was not present "
                f"in the training data. Known examples include: {known_values} ..."
            ),
        )


@router.post("/predict", response_model=YieldOutput)
def predict_yield(payload: YieldInput):
    """
    Predict crop yield for the given area, crop item, year, and
    environmental conditions, then persist the result to the database.
    """
    try:
        model, area_encoder, item_encoder = _load_yield_artifacts()

        area_encoded = _safe_encode(area_encoder, payload.area, "area")
        item_encoded = _safe_encode(item_encoder, payload.item, "item")

        features = np.array([[
            area_encoded,
            item_encoded,
            payload.year,
            payload.rainfall,
            payload.pesticides,
            payload.temperature,
        ]])

        prediction = model.predict(features)
        predicted_yield = float(round(prediction[0], 2))

        insert_yield_prediction(
            area=payload.area,
            item=payload.item,
            year=payload.year,
            rainfall=payload.rainfall,
            pesticides=payload.pesticides,
            temperature=payload.temperature,
            predicted_yield=predicted_yield,
        )

        return YieldOutput(
            predicted_yield=predicted_yield,
            message=f"Estimated yield for {payload.item} in {payload.area} "
                    f"({payload.year}) is {predicted_yield} hg/ha."
        )

    except HTTPException:
        raise
    except FileNotFoundError as e:
        raise HTTPException(status_code=503, detail=str(e))
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Yield prediction failed: {str(e)}")


@router.get("/history")
def yield_history(limit: int = 50):
    """Return the most recent yield prediction records."""
    try:
        return {"history": get_yield_predictions(limit=limit)}
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Failed to fetch yield history: {str(e)}")
